### ISSUE TITLE
IP Restriction not valid for quiz reviews

### ISSUE THREAD

**Issue by JasonEverling** [vadimonus/moodle-quizaccess_ipaddresslist#1]
Is there anyway to add a feature so that the IP Restrictions are honored for the quiz review? We can block them from taking the quiz at certain locations but they can still login somewhere else after the quiz and print/screen grab/copy the questions

**Comment by JasonEverling** [comment]
You can disregard this, it is configured in moodle core like that. I had to create a new function and edit quiz accessmanager and view/review pages to check before opening up the quiz review.

**Comment by vadimonus** [comment]
Excuse me for not responding for so long time. Moodle accessmanager does not allow special callbacks for review checks, but you can use setup_attempt_page function for checks.
example: 
    public function setup_attempt_page($page) {
        $attemptid = $page->url->param('attempt');
        if (empty($attemptid)) {
            return;
        }
        $attemptobj = quiz_attempt::create($attemptid);
        if ($attemptobj->is_finished()) {
           check for ip here and throw exception on error

And why not to disable it quiz settings attempt review after quiz, but enable it immediately after quiz? Your students will be able to open quiz review only in 2 minutes after quiz is finished, so they would have no time to open it in other place

**Comment by JasonEverling** [comment]
It's OK, I did find out it was a core moodle function in the way it works :( . I went ahead and used this method which is working great for now, added a new function and check. I will be refactorng to include a yes/no option on the core quiz itself.

https://github.com/bshp/moodle-bshp_patches/tree/master/mod/quiz

The reason we don't go that way, is because the teachers are paranoid that if a student is reviewing the quiz and another student is 1 foot away would look at their screen. So the class does not review it until everyone is finished.

**Comment by vadimonus** [comment]
I think you should create improvement ticket at tracker.moodle.org, describing the problem the same way you did it here. If core develpers decide, that this improvement should be done, i will help to prepare code to integration.

**Comment by JasonEverling** [comment]
@vadimonus If you wanted to take a look at what I have done and maybe send me some feedback, creating features from scratch is new for me. Right now we are using the fix/mod/quiz branch to force all reviews, I would like to get this part integrated into our version though so that way the teacher has the option and is not forced. Here is the branch with the feature, last 6 commits. [https://github.com/bshp/moodle/tree/feature/mod/quiz](https://github.com/bshp/moodle/tree/feature/mod/quiz)

**Comment by JasonEverling** [comment]
@vadimonus Maybe a checkbox next to each restriction instead of a Yes/No, I couldn't figure that part out though
