### ISSUE TITLE
3.11 compatibility

### ISSUE THREAD

**Issue by Badatos** [vadimonus/moodle-quizaccess_ipaddresslist#2]
Hello !
I just tested to install your plugin in the latest Moodle 3.11 version, and it seems it cannot be installed:

`Validating quizaccess_ipaddresslist ... Error`

Have you planned to make it compatible with Moodle 3.11 ?

**Comment by vadimonus** [comment]
Can you enable debug mode and provide full log ?

**Comment by Badatos** [comment]
I really don't know what happened yesterday.
I just tested again today, with the same archive file (quizaccess_ipaddresslist_moodle310_2021010300.zip), and it worked !

Sorry for the noise :/
