### ISSUE TITLE
Show allowed locations line by line instead of side by side

### ISSUE THREAD

**Issue by AntonT76** [vadimonus/moodle-quizaccess_ipaddresslist#3]
Hello,

we are using your plugin for restricted quiz settings for more than 15 different rooms. In the quiz settings the allowed locations will be shown side by side, eg:
[]Room 1[]Room 2[]Room 3[]Room 4[]Room 5[]Room 6[]Room 7[]Room 8[]Room 9 ....

It would be much easier and less error-prone if the allowed locations will be shown line by line, eg:
[]Room 1
[]Room 2
[]Room 3
[]Room 4
[]Room 5
[]Room 6
[]Room 7
[]Room 8
[]Room 9 ....

We are using Moodle 3.9 with boost theme - maybe it depends on the boost theme.

thanks, br, Anton

**Comment by vadimonus** [comment]
That's was by design in previous moodle versions. Fixed for boost theme in 1.3.1
