### ISSUE TITLE
Update for Moodle 4.*?

### ISSUE THREAD

**Issue by AntonT76** [vadimonus/moodle-quizaccess_ipaddresslist#4]
Dear @vadimonus,
we are using your plugin in our current Moodle installations (3.9) and we are planning an update in summer 2023 to Moodle 4.1. Are you also planning to update your plugin for Moodle 4.*? That would be great, because we use the plugin very often.

thx, br Anton

**Comment by vadimonus** [comment]
Currently i have no time to test this plugin on newer moodle versions. You may install and test this plugin on moodle 4.0 and 4.1 and report if it has any problems.
If any problem discovered, you may describe them in issue, so i can reproduce and fix it.
If you report, that plugin works correctly, i'll mark plugin as supporting 4.0 and 4.1.

Check both theme boost and classic, admin settings page and quiz settings page.

**Comment by AntonT76** [comment]
Dear @vadimonus 

thank you for your answer. I did some tests on Moodle 4.1.1:
- Installation: OK, no error message
- admin settings in Boost, Classic --> OK, no problems
- quiz settings in Boost, Classic --> OK, no problems

So, it seems to be that the plugin works correctly in 4.1. But I wasn't able to test it in 4.0 (actually I do not have any Moodle in version 4.0). Maybe there is another person who can do this tests in 4.0?

br, Anton

**Comment by vadimonus** [comment]
Marked as supporting 4.0 and 4.1
